### ISSUE TITLE
Returns to menu during gameplay

### ISSUE THREAD

**Issue by dailyskeptic** [kirjavascript/TetrisGYM#11] opened 2021-11-22 17:58 UTC
During play the game will exit to the menu screen. So far, I it has happened infrequently, (3) times, and has only occurred during standard Tetris play, seemingly at random. I am using original hardware (NES-001) with an Everdrive N8.

**Comment by kirjavascript** [comment] 2021-11-22 19:17
Hi!

Due to the large amount of playtime gym has had with no one else reporting it I suspect this is likely a hardware issue, especially if it is random. I cannot think of another mechanism that could trigger this really.

Does it happen on other tetris roms? If not does it still happen consistently with gym after testing the others? 

I'd advise to make sure the cartridge is securely inserted or clean the pins / connectors

**Comment by dailyskeptic** [comment] 2021-11-24 12:12
Everything should be clean. I've played a lot of V3 without any problems,
and I haven't had this issue with other Tetris ROMs, yet. I'm going to see
if it will repeat on different hardware, and try to get me details about
when happens, if it continues to happen.

**Comment by kirjavascript** [comment] 2021-12-23 17:15
Closing since 1 month has passed with no new reports.

If you can reproduce it consistently you can create a new issue.

**Closed by kirjavascript** 2021-12-23 17:15 UTC

**Comment by dailyskeptic** [comment] 2021-12-23 17:19
I do think it's hardware. I've but been able to reproduce on my top loader.
Thanks!
